### ISSUE TITLE
删除敏感词有问题 敏感词:中， 中华人， 中人。 删除中人时，函数不执行任何动作

### ISSUE THREAD

**Issue by longyongchun** [huayuego/wordfilter#4]
71 func (t *Trie) cycleDel(node *Node, chars []rune, index int) (shouldDel bool) {
 72     char := chars[index]
 73     l := len(chars)
 74     shouldDel = false
 75     if n, ok := node.Node[char]; ok {
 76         if index+1 < l {
 77             shouldDel = t.cycleDel(n, chars, index+1)
 78             if shouldDel {
 79                 if node.End || len(node.Node) != 0 { // 说明这是一个敏感词，不能删除
 80                     shouldDel = false
 81                 } else {
 82                     delete(node.Node, char)
 83                 }
 84             }
 85         } else if n.End {
 86             if len(n.Node) == 0 { // 是最后一个节点
 87                 shouldDel = true
 88                 delete(node.Node, char)
 89             } else { // 不是最后一个节点
 90                 n.End = false
 91             }   
 92         }   
 93     }   
 94     
 95     return
 96 }  
应该修改为以上函数

**Comment by elvin-lian** [comment]
谢谢。see #3
