### ISSUE TITLE
使用添加黑名单接口

### ISSUE THREAD

**Issue by speakphp** [huayuego/wordfilter#5]
我使用添加黑名单接口添加成功了 ， 然后我把服务给kill掉， 然后我看 磁盘文件 default.txt里面没有写入我添加的词？？？

**Comment by elvin-lian** [comment]
这个是没有写到文件的。只写到当前Tire内存中。

**Comment by tanteng** [comment]
对啊，这个问题怎么办，每次添加成功的敏感词，服务重启就失效了，有什么好的解决办法？
